{-# LANGUAGE CPP #-}
{-# LANGUAGE OverloadedStrings #-}

module Amoebius.Capacity.Phase29Mutation
  ( phase29MutationTargets
  ) where

import Data.Text (Text)

-- Compile-time production mutation selector.  Each Cabal flag changes the
-- production fold library, while the independently compiled oracle fixes the
-- exact fixture that must observe the changed result.
phase29MutationTargets :: Text -> Bool
#if defined(EXECUTION_ACCELERATOR_ACCELERATOR_DROP_DEVICE_COUNT_MUTANT)
phase29MutationTargets = (== "cuda-device-count")
#elif defined(EXECUTION_ACCELERATOR_ACCELERATOR_DROP_SOURCE_DOMAIN_MUTANT) || defined(EXECUTION_ACCELERATOR_ACCELERATOR_FAVORABLE_EPOCH_MUTANT) || defined(EXECUTION_ACCELERATOR_ACCELERATOR_SPLIT_UNSHARDED_MUTANT)
phase29MutationTargets = (== "cuda-unsharded-fragmentation")
#elif defined(EXECUTION_ACCELERATOR_ACCELERATOR_IGNORE_METAL_PROFILE_MUTANT)
phase29MutationTargets = (== "metal-profile")
#elif defined(EXECUTION_ACCELERATOR_ACCELERATOR_IGNORE_SHARD_SUM_MUTANT)
phase29MutationTargets = (== "cuda-shard-byte-sum")
#elif defined(EXECUTION_ACCELERATOR_ACCELERATOR_SHARE_DEVICE_MUTANT)
phase29MutationTargets = (== "accelerator-shared-owner")
#elif defined(EXECUTION_ACCELERATOR_ACCELERATOR_SPEND_RAW_VRAM_MUTANT)
phase29MutationTargets = (== "cuda-vram-reserve")
#elif defined(EXECUTION_ACCELERATOR_ACCELERATOR_TREAT_NONE_AS_CUDA_MUTANT)
phase29MutationTargets = (== "cuda-family-absent")
#elif defined(EXECUTION_ACCELERATOR_COPY_NEW_EXECUTION_AS_OLD_MUTANT) || defined(EXECUTION_ACCELERATOR_DROP_EXECUTION_OLD_REVISION_MUTANT) || defined(EXECUTION_ACCELERATOR_DROP_REMOVED_EXECUTION_MUTANT) || defined(EXECUTION_ACCELERATOR_RESOLVE_LATEST_EXECUTION_MUTANT)
phase29MutationTargets = (== "execution-prior-old-revision")
#elif defined(EXECUTION_ACCELERATOR_DROP_EXECUTION_REPLICA_MUTANT) || defined(EXECUTION_ACCELERATOR_INVENT_FIRST_DEPLOY_OLD_MUTANT)
phase29MutationTargets = (== "execution-replica-peak")
#elif defined(EXECUTION_ACCELERATOR_DROP_EXECUTION_SURGE_MUTANT)
phase29MutationTargets = (== "execution-rollout-surge")
#elif defined(EXECUTION_ACCELERATOR_ETCD_DROP_DEFRAG_MUTANT) || defined(EXECUTION_ACCELERATOR_ETCD_DROP_PREALLOCATED_NEXT_MUTANT) || defined(EXECUTION_ACCELERATOR_ETCD_DROP_SNAPSHOT_SAVE_MUTANT) || defined(EXECUTION_ACCELERATOR_ETCD_DROP_WAL_MUTANT)
phase29MutationTargets = (== "etcd-transition-physical")
#elif defined(EXECUTION_ACCELERATOR_IMAGE_DROP_INDEX_MUTANT)
phase29MutationTargets = (== "image-content-join")
#elif defined(EXECUTION_ACCELERATOR_IMAGE_DROP_MANIFEST_MUTANT)
phase29MutationTargets = (== "image-manifest-join")
#elif defined(EXECUTION_ACCELERATOR_IMAGE_DROP_SNAPSHOT_MUTANT)
phase29MutationTargets = (== "image-snapshot-join")
#elif defined(EXECUTION_ACCELERATOR_IMAGE_DROP_WORKSPACE_MUTANT)
phase29MutationTargets = (== "node-image-workspace")
#elif defined(EXECUTION_ACCELERATOR_IMAGE_IGNORE_MODEL_MUTANT)
phase29MutationTargets = (== "image-storage-model")
#elif defined(EXECUTION_ACCELERATOR_LAYOUT_ALLOW_ALIAS_MUTANT)
phase29MutationTargets = (== "filesystem-layout-alias")
#elif defined(EXECUTION_ACCELERATOR_LAYOUT_ENABLE_V1_SPLIT_IMAGE_MUTANT)
phase29MutationTargets = (== "split-image-containerd-v1")
#elif defined(EXECUTION_ACCELERATOR_LAYOUT_IGNORE_OBSERVATION_MUTANT)
phase29MutationTargets = (== "filesystem-layout-swapped")
#elif defined(EXECUTION_ACCELERATOR_PARTITION_DOUBLE_DEBIT_CHILD_MUTANT)
phase29MutationTargets = (== "partition-carve-alias")
#elif defined(EXECUTION_ACCELERATOR_PARTITION_DROP_SYSTEM_RESERVE_MUTANT) || defined(EXECUTION_ACCELERATOR_PARTITION_USE_VM_USABLE_AS_RAW_MUTANT)
phase29MutationTargets = (== "partition-parent")
#elif defined(EXECUTION_ACCELERATOR_PARTITION_MIX_VM_USABLE_MUTANT)
phase29MutationTargets = (== "partition-unit-mismatch")
#elif defined(EXECUTION_ACCELERATOR_PROVIDER_DEBIT_DURABLE_MUTANT) || defined(EXECUTION_ACCELERATOR_PROVIDER_REUSE_TEMPLATE_ID_MUTANT)
phase29MutationTargets = (== "root-ebs-volume-quota")
#elif defined(EXECUTION_ACCELERATOR_PROVIDER_SKIP_ALLOCATION_ROUNDING_MUTANT) || defined(EXECUTION_ACCELERATOR_PROVIDER_SKIP_PRESENTATION_MUTANT)
phase29MutationTargets = (== "root-ebs-bytes-quota")
#elif defined(EXECUTION_ACCELERATOR_PROVIDER_UNDER_SIZE_INSTANCE_STORE_MUTANT)
phase29MutationTargets = (== "instance-store-root")
#elif defined(EXECUTION_ACCELERATOR_RUNTIME_DROP_LARGEST_METADATA_MUTANT)
phase29MutationTargets = (== "runtime-nodefs")
#elif defined(EXECUTION_ACCELERATOR_RUNTIME_MISSING_MODEL_MUTANT)
phase29MutationTargets = (== "runtime-model")
#elif defined(EXECUTION_ACCELERATOR_RUNTIME_SCOPE_CONFUSION_MUTANT)
phase29MutationTargets = (== "runtime-scope-domain")
#elif defined(EXECUTION_ACCELERATOR_RUNTIME_SWAP_ROLE_MUTANT)
phase29MutationTargets = (== "runtime-imagefs")
#elif defined(EXECUTION_ACCELERATOR_SCHEDULER_BINDING_CRASH_RELEASE_MUTANT) || defined(EXECUTION_ACCELERATOR_SCHEDULER_TIMEOUT_RELEASE_MUTANT)
phase29MutationTargets = (== "scheduler-aggregate-root")
#elif defined(EXECUTION_ACCELERATOR_SCHEDULER_DROP_PAD_MUTANT)
phase29MutationTargets = (== "scheduler-projection")
#elif defined(EXECUTION_ACCELERATOR_SCHEDULER_PER_RECORD_CAS_MUTANT)
phase29MutationTargets = (== "scheduler-snapshot-cas")
#elif defined(EXECUTION_ACCELERATOR_BUILD_CACHE_BUDGET_MUTANT)
phase29MutationTargets = (== "build-cache-budget")
#elif defined(EXECUTION_ACCELERATOR_ENGINE_STORAGE_RESERVE_MUTANT)
phase29MutationTargets = (== "engine-storage-reserve")
#elif defined(EXECUTION_ACCELERATOR_MONITORING_VOLUME_BUDGET_MUTANT)
phase29MutationTargets = (== "monitoring-volume-budget")
#elif defined(EXECUTION_ACCELERATOR_PULUMI_EXECUTOR_CONCURRENCY_MUTANT)
phase29MutationTargets = (== "pulumi-executor-concurrency")
#else
phase29MutationTargets _ = False
#endif
