{-# LANGUAGE OverloadedStrings #-}

module Amoebius.Test.SuggestTest
  ( OptionalBranch (..)
  , SuggestInput (..)
  , SuggestError (..)
  , suggestTest
  , renderSuggestedDhall
  ) where

import Amoebius.Test.Credentials
import Amoebius.Test.Topology
import Data.Text (Text)
import Data.Text qualified as Text

data OptionalBranch = NoOptionalBranch | RegistryPublication | PulumiExecution | StorageMigration
  deriving stock (Eq, Ord, Show, Enum, Bounded)

data SuggestInput = SuggestInput
  { suggestSubstrate :: TestSubstrate
  , suggestSupply :: ResourceVector
  , suggestCredential :: TestCredential
  , suggestBranch :: OptionalBranch
  , suggestAcceleratorOffering :: Maybe Text
  }
  deriving stock (Eq, Show)

data SuggestError = NoRepresentativeTopologyFits ProvisionError
  deriving stock (Eq, Show)

suggestTest :: SuggestInput -> Either SuggestError ProvisionedTestTopology
suggestTest input = either (Left . NoRepresentativeTopologyFits) Right (provisionTestTopology topology)
 where
  topology = TestTopology
    { topologySubstrate = suggestSubstrate input
    , topologyCredential = suggestCredential input
    , topologyAllocations = [Allocation "phase54-retained" True (1024 * 1024 * 1024)]
    , topologyFaults = [KillWorker "worker-a" "phase54-failover"]
    , topologyExpectations = [Expectation "StandbyTakesOver" (Just "broker-stats"), Expectation "CrossZoneContinuity" Nothing]
    , topologyTeardownRequired = True
    , topologySupply = suggestSupply input
    , topologyDemand = branchDemand (suggestBranch input)
    , topologyAcceleratorRequirement = NoAccelerator
    , topologyAcceleratorOffering = suggestAcceleratorOffering input
    }

branchDemand :: OptionalBranch -> ResourceVector
branchDemand branch = ResourceVector 3000 3221225472 8589934592 durable cache 4 4 0 0
 where
  (durable, cache) = case branch of
    NoOptionalBranch -> (1073741824, 536870912)
    RegistryPublication -> (3221225472, 536870912)
    PulumiExecution -> (2147483648, 1073741824)
    StorageMigration -> (4294967296, 536870912)

renderSuggestedDhall :: ProvisionedTestTopology -> Text
renderSuggestedDhall provisioned = Text.unlines
  [ "-- generated by amoebius suggest-test; operator review required"
  , "{ substrate = \"" <> substrate <> "\""
  , ", credential = \"" <> credentialSecretName (topologyCredential topology) <> "\""
  , ", delegatedFailover = { target = \"worker-a\", subscription = \"phase54-failover\" }"
  , ", teardown = True"
  , "}"
  ]
 where
  topology = provisionedTopology provisioned
  substrate = case topologySubstrate topology of
    TestLinuxCpu -> "linux-cpu"
    TestLinuxCuda -> "linux-cuda"
    TestApple -> "apple"
    TestWindows -> "windows"
