{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Amoebius.Calculus.Artifact.Recipe (RecipeId (RecipeId))
import Amoebius.Calculus.Budget.Grant (Bytes (Bytes), Slots (Slots), allowance)
import Amoebius.Calculus.Composition
  ( append
  , artifactComponent
  , budgetComponent
  , calculusTag
  , compose
  , compositionKinds
  , compositionNames
  , compositionResource
  , evidenceComponent
  , everyCalculus
  , liftComponent
  , singleton
  , workflowComponent
  )
import Amoebius.Calculus.Evidence.Register (Register (PureRegister))
import Amoebius.Calculus.Lift.Layer (Layer (OnHost))
import Amoebius.Calculus.Workflow.Ledger (emptyLedger)
import Amoebius.Capacity.Types (ResourceVector (ResourceVector))
import Amoebius.Generate.CheckingCorpus
import Amoebius.Scope.Index qualified as CalculusScope
import Control.Monad (forM_, unless, when)
import Data.ByteString qualified as ByteString
import Data.List (sort)
import Data.Text (Text)
import Data.Text qualified as Text
import System.Directory
  ( doesFileExist
  , executable
  , getCurrentDirectory
  , getPermissions
  , makeAbsolute
  , setCurrentDirectory
  )
import System.Environment (getArgs)
import System.Exit (die)
import System.FilePath (makeRelative, normalise, splitDirectories, takeDirectory, (</>))
import ToolAndMutantGenerationOracle qualified as Oracle

artifactCount :: Int
artifactCount = 9

main :: IO ()
main = do
  root <- projectRoot
  setCurrentDirectory root
  arguments <- getArgs
  (outputArgument, runIdentity) <- case arguments of
    ["--output", output, "--run-id", runId] -> pure (output, Text.pack runId)
    _ -> die "usage: tool-and-mutant-generation-spec --output DIRECTORY --run-id ID"
  output <- makeAbsolute outputArgument
  checkMutantLoci
  checkIndependentOracle
  checkRefusalPairs root output
  buildRoot <- requireRight "build root" (mkBuildRoot root output runIdentity)
  generated <- requireRight "support corpus projection" supportCorpusProjection
  paths <- writeGeneratedCorpus buildRoot >>= requireRight "materialization"
  assertEqual "generated path count" artifactCount (length paths)
  forM_ (zip generated paths) $ \(artifact, path) -> do
    assertEqual "projected path" (normalise (artifactOutputPath buildRoot artifact)) (normalise path)
    present <- doesFileExist path
    assert present ("generated artifact absent: " <> path)
    bytes <- ByteString.readFile path
    assertEqual ("generated bytes " <> path) (generatedBytes artifact) bytes
    assert (pathContainedByBuildRoot root path) ("generated artifact escaped .build: " <> path)
    when (generatedClass artifact == CheckingTool) $ do
      permissions <- getPermissions path
      assert (executable permissions) ("checking tool is not executable: " <> path)
  checkClassRoots generated
  checkCalculus root
  putStrLn "tool-and-mutant-generation-calculus: PASS (5 kinds, 27 projected units)"
  putStrLn "tool-and-mutant-generation-spec: PASS (3 checking tools, 2 serialized cases, 3 mutation declarations, 1 Pulumi program, 9 content-addressed artifacts, 3 mutants)"

checkMutantLoci :: IO ()
checkMutantLoci = do
  let identities = map supportIdentity supportCorpus
      toolIdentities = filter ("tool." `Text.isPrefixOf`) identities
      mutationIdentities = filter ("mutant." `Text.isPrefixOf`) identities
  when (sort toolIdentities /= sort ["tool.validate-phase", "tool.check-documentation", "tool.check-source-closure"]) $
    die "tool-and-mutant-generation-mutant: RED missing-rule artifact-set-mismatch"
  when (sort mutationIdentities /= sort ["mutant.missing-rule", "mutant.drop-operator", "mutant.tracked-output"]) $
    die "tool-and-mutant-generation-mutant: RED drop-operator mutation-set-mismatch"
  when (outputPolicy /= BuildTree) $
    die "tool-and-mutant-generation-mutant: RED tracked-output output-policy-refused"

checkIndependentOracle :: IO ()
checkIndependentOracle = do
  let actual =
        [ Oracle.OracleArtifact
            (supportIdentity artifact)
            (classTag (supportClass artifact))
            (supportLogicalPath artifact)
            (supportBytes artifact)
        | artifact <- supportCorpus
        ]
  assertEqual "independent exact artifact registry" Oracle.expectedArtifacts actual
  let counts =
        [ (tag, length (filter ((== tag) . classTag . supportClass) supportCorpus))
        | tag <- ["checking-tool", "serialized-test-case", "mutation-body", "pulumi-program"]
        ]
  assertEqual "independent class counts" Oracle.expectedClassCounts counts

checkRefusalPairs :: FilePath -> FilePath -> IO ()
checkRefusalPairs root output = do
  let observations =
        [ ("relative-project", eitherTag (mkBuildRoot "." output "clean"))
        , ("authored-output", eitherTag (mkBuildRoot root root "clean"))
        , ("path-run-identity", eitherTag (mkBuildRoot root output "../escape"))
        ]
  assertEqual "paired output-root refusals" Oracle.expectedRefusals observations
  _ <- requireRight "paired positive output root" (mkBuildRoot root output "clean")
  pure ()

eitherTag :: Either GenerationProblem value -> Text
eitherTag value = case value of
  Left problem -> Text.pack (show problem)
  Right _ -> "accepted"

checkClassRoots :: [GeneratedArtifact] -> IO ()
checkClassRoots artifacts =
  forM_ artifacts $ \artifact ->
    let parts = splitDirectories (generatedPath artifact)
        expected = case generatedClass artifact of
          CheckingTool -> ["tools"]
          SerializedTestCase -> ["test-corpora"]
          MutationBody -> ["test-corpora", "mutants"]
          PulumiProgram -> ["pulumi"]
    in assert (expected == take (length expected) parts)
         ("wrong generated class root for " <> Text.unpack (generatedIdentity artifact))

pathContainedByBuildRoot :: FilePath -> FilePath -> Bool
pathContainedByBuildRoot root path =
  case splitDirectories (makeRelative root path) of
    ".build" : _ -> True
    _ -> False

classTag :: ArtifactClass -> Text
classTag artifactClass = case artifactClass of
  CheckingTool -> "checking-tool"
  SerializedTestCase -> "serialized-test-case"
  MutationBody -> "mutation-body"
  PulumiProgram -> "pulumi-program"

checkCalculus :: FilePath -> IO ()
checkCalculus _root = do
  tenant <- requireRight "calculus tenant" (CalculusScope.trustedTenant "tool-generation-calculus-tenant")
  subject <- requireRight "calculus subject" (CalculusScope.trustedSubject tenant "tool-generation-calculus-subject")
  membership <- requireRight "calculus membership" (CalculusScope.activeMembership tenant subject)
  action <- requireRight "calculus request scope" $
    CalculusScope.withRequestScope tenant subject membership $ \scope -> do
      let resources :: Int -> ResourceVector
          resources count = ResourceVector 1 (fromIntegral count) 0 0
          artifact = artifactComponent scope "generated-checking-corpus" (resources artifactCount)
            (RecipeId "tool-and-mutant-generation" (fromIntegral artifactCount))
          budget = budgetComponent scope "closed-generation-budget" (resources 2)
            (allowance (Bytes 1) (Slots 1) (Bytes 1))
          lift = liftComponent scope "haskell-support-declarations" (resources artifactCount) OnHost
          workflow = workflowComponent scope "materialization-workflow" (resources 4) emptyLedger
          evidence = evidenceComponent scope "mutant-evidence" (resources 3) PureRegister
          composition = append (compose artifact budget) (append (compose lift workflow) (singleton evidence))
          ResourceVector cpu memory ephemeral pods = compositionResource composition
      assertEqual "five calculus kinds" everyCalculus (compositionKinds composition)
      assertEqual
        "component names"
        [ "generated-checking-corpus"
        , "closed-generation-budget"
        , "haskell-support-declarations"
        , "materialization-workflow"
        , "mutant-evidence"
        ]
        (compositionNames composition)
      assertEqual "calculus kind tags" ["artifact", "budget", "lift", "workflow", "evidence"] (map calculusTag (compositionKinds composition))
      assertEqual "calculus resource vector" (ResourceVector 5 27 0 0) (ResourceVector cpu memory ephemeral pods)
  action

requireRight :: Show problem => String -> Either problem value -> IO value
requireRight label = either (die . ((label <> ": ") <>) . show) pure

assert :: Bool -> String -> IO ()
assert condition message = unless condition (die message)

assertEqual :: (Eq value, Show value) => String -> value -> value -> IO ()
assertEqual label wanted actual = unless (wanted == actual) $
  die (label <> ": expected " <> show wanted <> ", got " <> show actual)

projectRoot :: IO FilePath
projectRoot = getCurrentDirectory >>= go
 where
  go path = do
    found <- doesFileExist (path </> "cabal.project")
    if found
      then makeAbsolute path
      else
        let parent = takeDirectory path
        in if parent == path then die "tool-and-mutant-generation-root" else go parent
