{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Amoebius.Calculus.Artifact.Recipe (RecipeId (RecipeId))
import Amoebius.Calculus.Budget.Grant (Bytes (Bytes), Slots (Slots), allowance)
import Amoebius.Calculus.Composition
  ( append
  , artifactComponent
  , budgetComponent
  , calculusTag
  , compose
  , compositionKinds
  , compositionNames
  , compositionResource
  , evidenceComponent
  , everyCalculus
  , liftComponent
  , singleton
  , workflowComponent
  )
import Amoebius.Calculus.Evidence.Register (Register (PureRegister))
import Amoebius.Calculus.Lift.Layer (Layer (OnHost))
import Amoebius.Calculus.Workflow.Ledger (emptyLedger)
import Amoebius.Capacity.Types (ResourceVector (ResourceVector))
import Amoebius.Generate.CheckingCorpus
import Amoebius.Scope.Index qualified as CalculusScope
import Control.Monad (forM_, unless, when)
import Data.ByteString qualified as ByteString
import Data.Text qualified as Text
import System.Directory (doesFileExist, getCurrentDirectory, setCurrentDirectory)
import System.Environment (getArgs)
import System.Exit (die)
import System.FilePath ((</>), takeDirectory)

toolCount :: Int
toolCount = 234

mutationCount :: Int
mutationCount = 371

artifactCount :: Int
artifactCount = toolCount + mutationCount

main :: IO ()
main = do
  root <- projectRoot
  setCurrentDirectory root
  arguments <- getArgs
  output <- case arguments of
    ["--output", path] -> pure path
    _ -> die "usage: tool-and-mutant-generation-spec --output DIRECTORY"
  verifyCustody root
  tools <- loadTools root
  mutations <- loadMutations root
  when (length tools /= toolCount) $
    die "tool-and-mutant-generation-mutant: RED missing_rule checker-rule-missing"
  when (length mutations /= mutationCount) $
    die "tool-and-mutant-generation-mutant: RED drop_operator mutation-operator-missing"
  case generationDefect of
    Just defect -> die defect
    Nothing -> pure ()
  when (outputPolicy /= BuildTree) $
    die "tool-and-mutant-generation-mutant: RED commit_emitted generated-artifact-tracked"
  let artifacts = generatedCorpus tools mutations
  assertEqual "generated artifact count" artifactCount (length artifacts)
  writeGeneratedCorpus output artifacts
  forM_ artifacts $ \artifact -> do
    let target = output </> generatedPath artifact
    present <- doesFileExist target
    assert present ("generated artifact absent: " <> generatedPath artifact)
    actual <- ByteString.readFile target
    assertEqual ("generated bytes " <> generatedPath artifact) (generatedBytes artifact) actual
  checkCalculus root
  putStrLn "tool-and-mutant-generation-calculus: PASS (5 kinds, 1219 projected units)"
  putStrLn "tool-and-mutant-generation-spec: PASS (234 tool sources, 371 mutation declarations, 605 artifacts, 3 mutants)"

loadTools :: FilePath -> IO [ToolDeclaration]
loadTools root = do
  rows <- loadTable (root </> "test/oracle/tool_and_mutant_generation/tool_inventory.tsv")
  traverse parse rows
  where
    parse fields = case fields of
      [path, kind, concern] -> do
        bytes <- ByteString.readFile (root </> path)
        pure ToolDeclaration
          { toolSourcePath = path
          , toolKind = kind
          , toolConcern = concern
          , toolSourceBytes = bytes
          }
      _ -> die ("invalid tool inventory row: " <> show fields)

loadMutations :: FilePath -> IO [MutationDeclaration]
loadMutations root = do
  rows <- loadTable (root </> "test/oracle/tool_and_mutant_generation/mutation_inventory.tsv")
  traverse parse rows
  where
    parse fields = case fields of
      [body, capability, mutant, operator, positive] -> do
        bytes <- ByteString.readFile (root </> body)
        pure MutationDeclaration
          { mutationBodyPath = body
          , mutationCapability = capability
          , mutationName = mutant
          , mutationOperator = operator
          , mutationPositiveSeed = positive
          , mutationBodyBytes = bytes
          }
      _ -> die ("invalid mutation inventory row: " <> show fields)

checkCalculus :: FilePath -> IO ()
checkCalculus root = do
  expected <- loadTable (root </> "test/oracle/tool_and_mutant_generation/calculus_projection.tsv")
  tenant <- requireRight "calculus tenant" (CalculusScope.trustedTenant "tool-generation-calculus-tenant")
  subject <- requireRight "calculus subject" (CalculusScope.trustedSubject tenant "tool-generation-calculus-subject")
  membership <- requireRight "calculus membership" (CalculusScope.activeMembership tenant subject)
  action <- requireRight "calculus request scope" $
    CalculusScope.withRequestScope tenant subject membership $ \scope -> do
      let resources :: Int -> ResourceVector
          resources count = ResourceVector 1 (fromIntegral count) 0 0
          counts = [artifactCount, 2, artifactCount, 4, 3]
          artifact = artifactComponent scope "generated-checking-corpus" (resources artifactCount)
            (RecipeId "tool-and-mutant-generation" (fromIntegral artifactCount))
          budget = budgetComponent scope "closed-generation-budget" (resources 2)
            (allowance (Bytes 1) (Slots 1) (Bytes 1))
          lift = liftComponent scope "tool-and-mutation-declarations" (resources artifactCount) OnHost
          workflow = workflowComponent scope "equivalence-workflow" (resources 4) emptyLedger
          evidence = evidenceComponent scope "mutant-evidence" (resources 3) PureRegister
          composition = append (compose artifact budget) (append (compose lift workflow) (singleton evidence))
          ResourceVector cpu memory ephemeral pods = compositionResource composition
          render = Text.unpack . Text.intercalate ","
          actual =
            [ ["calculus-kinds", render (map calculusTag (compositionKinds composition))]
            , ["component-names", render (compositionNames composition)]
            , ["projection-counts", render (map (Text.pack . show) counts)]
            , ["resource-vector", render (map (Text.pack . show) [cpu, memory, ephemeral, pods])]
            ]
      assertEqual "five calculus kinds" everyCalculus (compositionKinds composition)
      assertEqual "tool generation calculus projection" expected actual
  action

verifyCustody :: FilePath -> IO ()
verifyCustody root = do
  rows <- loadTable (root </> "test/oracle/preimplementation_artifacts.tsv")
  let phaseRows = [fields | fields@(phase : _) <- rows, phase == "30"]
  assertEqual "Phase-0 custody" 5 (length phaseRows)
  forM_ phaseRows $ \row -> case row of
    (_phase : _kind : path : _) -> do
      present <- doesFileExist (root </> path)
      assert present ("missing " <> path)
    _ -> die "bad Phase-30 custody row"

loadTable :: FilePath -> IO [[String]]
loadTable path = do
  rows <- lines <$> readFile path
  case rows of
    [] -> die ("empty table: " <> path)
    _header : body -> pure (map splitTabs body)

splitTabs :: String -> [String]
splitTabs value = case break (== '\t') value of
  (field, []) -> [field]
  (field, _ : rest) -> field : splitTabs rest

requireRight :: Show problem => String -> Either problem value -> IO value
requireRight label = either (die . ((label <> ": ") <>) . show) pure

assert :: Bool -> String -> IO ()
assert condition message = unless condition (die message)

assertEqual :: (Eq value, Show value) => String -> value -> value -> IO ()
assertEqual label wanted actual = unless (wanted == actual) $
  die (label <> ": expected " <> show wanted <> ", got " <> show actual)

projectRoot :: IO FilePath
projectRoot = getCurrentDirectory >>= go
  where
    go path = do
      found <- doesFileExist (path </> "cabal.project")
      if found then pure path else
        let parent = takeDirectory path
        in if parent == path then die "tool-and-mutant-generation-root" else go parent
