module Main (main) where

import Control.Monad (unless)
import DocumentationOracle (runDocumentationOracle)
import PolicyContractOracle (runPolicyContractOracle)
import SelectorCli (SelectorSuite (..), runSelectorCli, selectorSuite)

main :: IO ()
main =
  runSelectorCli
    ( (selectorSuite "validation-documentation-internal-selector-component" runDocumentationOracle runSelected)
        { suiteSelectorNames = selectorNames
        , suiteRunControl = Just (const runPolicyContractOracle)
        , suiteAssignments =
            [ (selector, ["documentation-oracle:" <> selector], "PolicyContractOracle")
            | selector <- selectorNames
            ]
        }
    )

runSelected :: String -> IO ()
runSelected selector = do
  unless (elem selector selectorNames) (fail ("unknown documentation-internal selector: " <> selector))
  runDocumentationOracle

selectorNames :: [String]
selectorNames =
  [ "VALIDATION_DOCUMENT_ARCHIVE_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_BACKLINK_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_CLAUDE_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_CORPUS_DISCOVERY_COMPOSITION_MUTANT"
  , "VALIDATION_DOCUMENT_CORPUS_DOCUMENT_COMPOSITION_MUTANT"
  , "VALIDATION_DOCUMENT_CORPUS_PHASE_CONTRACT_COMPOSITION_MUTANT"
  , "VALIDATION_DOCUMENT_DUPLICATE_PATH_BYPASS_MUTANT"
  , "VALIDATION_DOCUMENT_DUPLICATE_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_EMPTY_DISCOVERY_BYPASS_MUTANT"
  , "VALIDATION_DOCUMENT_EMPTY_DISCOVERY_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_GOVERNED_AGENTS_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_GOVERNED_CLAUDE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_GOVERNED_CRASH_SUMMARY_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_GOVERNED_DOCUMENTS_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_GOVERNED_PLAN_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_GOVERNED_README_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_BLOCK_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_CLOSE_CARDINALITY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_CLOSE_LIMIT_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_CLOSE_TAG_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_DETAILS_BLOCK_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_DETAILS_CARDINALITY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_DETAILS_FINDING_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_DETAILS_LIMIT_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_DETAILS_TAG_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_FIELD_BLOCK_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_FIELD_FINDING_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_LEAD_AFTER_READ_THIS_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_LEAD_BEFORE_DETAILS_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_LEAD_NONBLANK_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_LEAD_NONQUOTE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_METADATA_CLOSE_LIMIT_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_METADATA_GENERATED_CLOSE_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_METADATA_REFERENCED_GENERATED_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_METADATA_STATUS_SUPERSEDES_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_METADATA_SUMMARY_STATUS_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_METADATA_SUPERSEDES_REFERENCED_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_NONBLANK_PREDICATE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_NONBLANK_STRIP_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_BEFORE_DETAILS_FILTER_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_DETAILS_ROUTE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_DETAILS_SUMMARY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_LEAD_EXISTENCE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_PURPOSE_READ_THIS_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_READ_THIS_DETAILS_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ORIENTATION_TITLE_PURPOSE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_PURPOSE_BLOCK_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_PURPOSE_CARDINALITY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_PURPOSE_LIMIT_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_PURPOSE_PREFIX_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_PURPOSE_VALUE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_READ_THIS_BLOCK_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_READ_THIS_CARDINALITY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_READ_THIS_LIMIT_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_READ_THIS_PREFIX_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_READ_THIS_VALUE_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_SUMMARY_CARDINALITY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_SUMMARY_LIMIT_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_SUMMARY_TAG_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_TITLE_BLOCK_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_TITLE_CARDINALITY_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_TITLE_FIRST_NONBLANK_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_TITLE_PREFIX_MUTANT"
  , "VALIDATION_DOCUMENT_HEADER_VISIBLE_LIMIT_THRESHOLD_MUTANT"
  , "VALIDATION_DOCUMENT_INPUT_ENVELOPE_ROUTE_BYPASS_MUTANT"
  , "VALIDATION_DOCUMENT_INVENTORY_COUNT_BYPASS_MUTANT"
  , "VALIDATION_DOCUMENT_INVENTORY_DIGEST_BYPASS_MUTANT"
  , "VALIDATION_DOCUMENT_INVENTORY_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_LINK_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_MARKDOWN_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_METADATA_STATUS_AUTHORITATIVE_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_METADATA_STATUS_DEPRECATED_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_METADATA_STATUS_LEGAL_ORDER_MUTANT"
  , "VALIDATION_DOCUMENT_METADATA_STATUS_REFERENCE_DROP_MUTANT"
  , "VALIDATION_DOCUMENT_NORMALIZE_BACKSLASH_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_NORMALIZE_DOT_PREFIX_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_OUTPUT_CORPUS_REFUSAL_RETENTION_MUTANT"
  , "VALIDATION_DOCUMENT_OUTPUT_DISCOVERY_REFUSAL_RETENTION_MUTANT"
  , "VALIDATION_DOCUMENT_OUTPUT_INVENTORY_REFUSAL_RETENTION_MUTANT"
  , "VALIDATION_DOCUMENT_OUTPUT_MANDATORY_FINDING_LIMIT_BYPASS_MUTANT"
  , "VALIDATION_DOCUMENT_OUTPUT_STRUCTURE_REFUSAL_RETENTION_MUTANT"
  , "VALIDATION_DOCUMENT_OWNER_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_AGENTS_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_CLAUDE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_CORPUS_ROUTE_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_CRASH_SUMMARY_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_DOCUMENTS_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_FINDINGS_AFTER_BOUND_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_PLAN_OMISSION_MUTANT"
  , "VALIDATION_DOCUMENT_REQUIRED_README_OMISSION_MUTANT"
  ]

