module Amoebius.Formal.EmitTLA
  ( Tla (..)
  , Cfg (..)
  , RenderMode (..)
  , emitTLA
  , emitTLAWith
  , renderExpr
  ) where

import Amoebius.Formal.Model
import Data.List (intercalate, sortOn)
import qualified Data.Map.Strict as Map

newtype Tla = Tla {unTla :: String}
  deriving stock (Eq, Ord, Show)

newtype Cfg = Cfg {unCfg :: String}
  deriving stock (Eq, Ord, Show)

data RenderMode
  = Correct
  | DropUnchanged
  | ForAllAsExists
  | StrongAsWeak
  | AlwaysAsEventually
  deriving stock (Eq, Ord, Show)

emitTLA :: Model -> (Tla, Cfg)
emitTLA = emitTLAWith Correct

emitTLAWith :: RenderMode -> Model -> (Tla, Cfg)
emitTLAWith mode model = (Tla (renderModule mode model), Cfg (renderCfg model))

renderModule :: RenderMode -> Model -> String
renderModule mode model = unlines . concat $
  [ [ "---- MODULE " <> modelName model <> " ----"
    , "\\* GENERATED by amoebius dev model from Model " <> modelName model <> "; do not edit by hand."
    , "EXTENDS Integers, FiniteSets, TLC"
    , ""
    ]
  , renderConstants model
  , ["VARIABLES " <> intercalate ", " (modelVariables model)]
  , ["vars == <<" <> intercalate ", " (modelVariables model) <> ">>", ""]
  , renderInit mode model
  , concatMap (renderAction mode model) (modelActions model)
  , renderNext model
  , concatMap (\named -> renderConjunctDefinition mode (namedExprName named) (flattenAnd (namedExprBody named))) (modelInvariants model)
  , maybe [] (\named -> renderConjunctDefinition mode (namedExprName named) (flattenAnd (namedExprBody named))) (modelConstraint model)
  , renderSpec mode model
  , renderProperties mode (modelProperties model)
  , ["===="]
  ]

renderConstants :: Model -> [String]
renderConstants model
  | null (modelConstants model) = []
  | otherwise = ["CONSTANTS " <> intercalate ", " (map fst (modelConstants model))]

renderConjunctDefinition :: RenderMode -> Name -> [Expr] -> [String]
renderConjunctDefinition mode name conjuncts =
  [name <> " =="] <> map ("  /\\ " <>) (map (renderExprWith mode) conjuncts) <> [""]

renderInit :: RenderMode -> Model -> [String]
renderInit mode model =
  ["Init =="]
    <> ["  /\\ " <> name <> " = " <> renderExprWith mode expr | (name, expr) <- modelInit model]
    <> [""]

renderAction :: RenderMode -> Model -> Action -> [String]
renderAction mode model action =
  [actionHeader action <> " =="]
    <> map ("  /\\ " <>) (parameterGuards <> actionGuards <> effects <> unchanged)
    <> [""]
  where
    parameterGuards =
      [ renderExprWith mode (FiniteSetMembership (Ref (parameterName parameter)) (parameterDomain parameter))
      | parameter <- actionParameters action
      ]
    actionGuards =
      maybe [] (map (renderExprWith mode) . flattenAnd) (modelExpansionLimit model)
        <> map (renderExprWith mode) (flattenAnd (actionGuard action))
    effects =
      [ name <> "' = " <> renderExprWith mode expr
      | name <- modelVariables model
      , Just expr <- [lookup name (actionEffects action)]
      ]
    unaffected = filter (`notElem` map fst (actionEffects action)) (modelVariables model)
    unchanged
      | null unaffected || mode == DropUnchanged = []
      | otherwise = ["UNCHANGED <<" <> intercalate ", " unaffected <> ">>"]

actionHeader :: Action -> String
actionHeader action = actionName action <> case actionParameters action of
  [] -> ""
  parameters -> "(" <> intercalate ", " (map parameterName parameters) <> ")"

renderNext :: Model -> [String]
renderNext model = ["Next =="] <> map ("  \\/ " <>) rendered <> [""]
  where
    rendered = map renderActionCall (modelActions model)
    renderActionCall action = case actionParameters action of
      [] -> actionName action
      parameters ->
        foldr
          (\parameter body -> "(\\E " <> parameterName parameter <> " \\in " <> renderExpr (parameterDomain parameter) <> " : " <> body <> ")")
          (actionName action <> "(" <> intercalate ", " (map parameterName parameters) <> ")")
          parameters

renderSpec :: RenderMode -> Model -> [String]
renderSpec mode model =
  ["Spec ==", "  /\\ Init", "  /\\ [][Next]_vars"]
    <> map ("  /\\ " <>) (map (renderFairness mode model) (modelFairness model))
    <> [""]

renderFairness :: RenderMode -> Model -> Fairness -> String
renderFairness mode model fairness = case findAction (fairnessAction fairness) of
  Nothing -> "FALSE \\* invalid fairness reference: " <> fairnessAction fairness
  Just action -> foldr quantify call (actionParameters action)
    where
      kind = case (mode, fairnessKind fairness) of
        (StrongAsWeak, StrongFair) -> "WF_vars"
        (_, WeakFair) -> "WF_vars"
        (_, StrongFair) -> "SF_vars"
      call = kind <> "(" <> actionName action <> arguments (actionParameters action) <> ")"
      quantify parameter body =
        "(\\A " <> parameterName parameter <> " \\in " <> renderExprWith mode (parameterDomain parameter) <> " : " <> stripOuter body <> ")"
      arguments [] = ""
      arguments parameters = "(" <> intercalate ", " (map parameterName parameters) <> ")"
      stripOuter text = text
  where
    findAction name = Map.lookup name (Map.fromList [(actionName action, action) | action <- modelActions model])

renderProperties :: RenderMode -> [Property] -> [String]
renderProperties mode properties =
  [propertyName property <> " == " <> renderTemporal mode (propertyTemporal property) | property <- properties]
    <> if null properties then [] else [""]

renderTemporal :: RenderMode -> Temporal -> String
renderTemporal mode temporal = case temporal of
  Always expr
    | mode == AlwaysAsEventually -> "<>(" <> renderExprWith mode expr <> ")"
    | otherwise -> "[](" <> renderExprWith mode expr <> ")"
  Eventually expr -> "<>" <> temporalOperand (renderExprWith mode expr)
  LeadsTo left right -> "(" <> renderExprWith mode left <> " ~> " <> renderExprWith mode right <> ")"
  where
    temporalOperand rendered@('(' : _) = rendered
    temporalOperand rendered = "(" <> rendered <> ")"

renderCfg :: Model -> String
renderCfg model = unlines . concat $
  [ renderCfgConstants (modelConstants model)
  , ["SPECIFICATION Spec"]
  , map (("INVARIANT " <>) . namedExprName) (modelInvariants model)
  , map (("PROPERTY " <>) . propertyName) (modelProperties model)
  , maybe [] (pure . ("CONSTRAINT " <>) . namedExprName) (modelConstraint model)
  , ["CHECK_DEADLOCK " <> if modelCheckDeadlock model then "TRUE" else "FALSE"]
  ]

renderCfgConstants :: [(Name, Value)] -> [String]
renderCfgConstants [] = []
renderCfgConstants constants =
  ["CONSTANT"] <> ["  " <> name <> " = " <> renderValue value | (name, value) <- constants]

renderExpr :: Expr -> String
renderExpr = renderExprWith Correct

renderExprWith :: RenderMode -> Expr -> String
renderExprWith mode expression = case expression of
  Literal value -> renderValue value
  Ref name -> name
  Not expr -> "~(" <> render expr <> ")"
  And exprs -> parenthesized "/\\" exprs
  Or exprs -> parenthesized "\\/" exprs
  Implies left right -> binary "=>" left right
  Equal left right -> binary "=" left right
  NotEqual left right -> binary "#" left right
  ArithmeticComparison comparison left right -> binary (comparisonOperator comparison) left right
  Add left right -> binary "+" left right
  Subtract left right -> binary "-" left right
  FiniteSet exprs -> "{" <> intercalate ", " (map render exprs) <> "}"
  SetUnion left right -> binary "\\cup" left right
  SetDifference left right -> binary "\\" left right
  Cardinality expr -> "Cardinality(" <> render expr <> ")"
  FiniteSetMembership element domain -> binary "\\in" element domain
  FiniteQuantifier quantifier binder domain predicate ->
    "(" <> quantifierOperator mode quantifier <> " " <> binder <> " \\in " <> render domain <> " : " <> render predicate <> ")"
  FunctionLiteral binder domain body ->
    "[" <> binder <> " \\in " <> render domain <> " |-> " <> render body <> "]"
  FunctionUpdate function key value ->
    "[" <> render function <> " EXCEPT ![" <> render key <> "] = " <> render value <> "]"
  FunctionApplication function key -> render function <> "[" <> render key <> "]"
  IfThenElse condition whenTrue whenFalse ->
    "(IF " <> render condition <> " THEN " <> render whenTrue <> " ELSE " <> render whenFalse <> ")"
  where
    render = renderExprWith mode
    binary operator left right = "(" <> render left <> " " <> operator <> " " <> render right <> ")"
    parenthesized "/\\" [] = "TRUE"
    parenthesized "\\/" [] = "FALSE"
    parenthesized operator exprs = "(" <> intercalate (" " <> operator <> " ") (map render exprs) <> ")"

comparisonOperator :: Comparison -> String
comparisonOperator comparison = case comparison of
  LessThan -> "<"
  LessThanOrEqual -> "<="
  GreaterThan -> ">"
  GreaterThanOrEqual -> ">="

quantifierOperator :: RenderMode -> Quantifier -> String
quantifierOperator ForAllAsExists ForAll = "\\E"
quantifierOperator _ ForAll = "\\A"
quantifierOperator _ Exists = "\\E"

renderValue :: Value -> String
renderValue value = case value of
  BoolValue True -> "TRUE"
  BoolValue False -> "FALSE"
  IntValue integer -> show integer
  AtomValue atom -> show atom
  SetValue values -> "{" <> intercalate ", " (map renderValue (sortOn renderValue values)) <> "}"
  FunctionValue pairs ->
    "(" <> intercalate " @@ " [renderValue key <> " :> " <> renderValue result | (key, result) <- sortOn (renderValue . fst) pairs] <> ")"

flattenAnd :: Expr -> [Expr]
flattenAnd (And exprs) = concatMap flattenAnd exprs
flattenAnd expr = [expr]
