variable "vm_name" {}
variable "public_key_openssh" {}
variable "ssh_user" {}
variable "image" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "zone" {}
variable "workspace" {}
