module Main (main) where

import PhaseSemanticContractOracle (runPhaseSemanticContractOracle)
import PolicyContractOracle (runPolicyContractOracle)
import SelectorCli (SelectorSuite (..), runSelectorCli, selectorSuite)
import Control.Monad (unless)

main :: IO ()
main =
  runSelectorCli
    ( (selectorSuite "validation-phase-semantic-selector-component" runPhaseSemanticContractOracle runSelected)
        { suiteSelectorNames = selectorNames
        , suiteRunControl = Just (const runPolicyContractOracle)
        , suiteAssignments =
            [ (selector, ["phase-semantic-oracle:" <> selector], "PolicyContractOracle")
            | selector <- selectorNames
            ]
        }
    )

runSelected :: String -> IO ()
runSelected selector = do
  unless (selector `elem` selectorNames) (fail ("unknown phase-semantic selector: " <> selector))
  runPhaseSemanticContractOracle

selectorNames :: [String]
selectorNames =
  [ "VALIDATION_PHASE_IDENTITY_PATH_DRIFT_MUTANT"
  , "VALIDATION_PHASE_IDENTITY_RESOURCE_MEMBERSHIP_DRIFT_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_DIAGNOSTIC_RESIDUE_REMOVAL_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_GAP_ACCEPTANCE_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_HARDWARE_METADATA_SWAP_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_COMMENT_SPLICE_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_CONTAINER_PREFIX_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_GATE_TABLE_FRAME_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_INDENTED_CODE_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_OPAQUE_BOUNDARY_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_PREDECESSOR_TRAILING_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_PSEUDO_FENCE_CLOSE_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_RAW_HTML_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_TRACKER_DELIMITER_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_TRACKER_DELIMITER_SHAPE_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_TRACKER_HEADER_WILDCARD_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_TRACKER_LIMIT_PIPE_ONLY_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_TRACKER_ROW_DISCOVERY_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_UNKNOWN_PATH_DISCOVERY_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_JOIN_UNRESOLVED_SUBSTRING_BYPASS_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_LEGACY_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_LEGACY_ROW_SWAP_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_OMISSION_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_PHASE49_SOURCE_GUARD_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_PHASE50_HANDOFF_GUARD_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_PHASE51_FAKE_GUARD_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_PHASE52_HARDWARE_GUARD_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_PREDECESSOR_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_PROVIDER_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_RESOURCE_DIAGNOSTIC_REMOVAL_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_RESOURCE_FIELD_IDENTITY_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_RESOURCE_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_SLOT_OMISSION_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_STAGE_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_SWAP_MUTANT"
  , "VALIDATION_PHASE_SEMANTIC_UNEXPECTED_CRITICAL_GUARD_MUTANT"
  ]
