{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}

module Amoebius.Image.RenderDockerfile
  ( Dockerfile (..)
  , renderDockerfile
  ) where

import Amoebius.Image.BakeInventory
import Data.Char (isAlphaNum)
import Data.Text (Text)
import Data.Text qualified as Text

newtype Dockerfile = Dockerfile {dockerfileText :: Text}
  deriving stock (Eq, Show)

renderDockerfile :: BakeCatalog -> Either CatalogError Dockerfile
renderDockerfile catalog = do
  validateBakeCatalog catalog
  pure . Dockerfile . Text.unlines $
    [ "# syntax=docker/dockerfile:1.7"
    , "# GENERATED BY Amoebius.Image.RenderDockerfile FROM dhall/amoebius/BakeCatalog.dhall; DO NOT EDIT"
    ]
      <> concatMap renderSource indexedCopies
      <> [ "FROM " <> catalog.baseImage <> "@" <> catalog.baseDigest <> " AS amoebius-base"
         , "ARG TARGETARCH"
         , "LABEL org.opencontainers.image.title=\"amoebius monocontainer\""
         , "LABEL io.amoebius.bake-catalog=\"dhall/amoebius/BakeCatalog.dhall\""
         ]
      <> concatMap renderCopies indexedCopies
      <> fmap renderBuilt indexedBuilt
      <> fmap renderEnvironment catalog.runtimeEnvironment
      <> [ "USER 65532:65532"
         , "ENTRYPOINT [\"/usr/bin/amoebius\"]"
         ]
 where
  indexedCopies = [(index, source) | (index, CopyOci source) <- zip [0 :: Int ..] (catalogSteps catalog)]
  indexedBuilt = [(index, built) | (index, BuildProduct built) <- zip [0 :: Int ..] (catalogSteps catalog)]
  alias index source = "source_" <> Text.pack (show index) <> "_" <> sanitize source.name
  renderSource (index, source) =
    [ "FROM " <> source.sourceImage <> "@" <> source.sourceDigest <> " AS " <> alias index source ]
  renderCopies (index, source) =
    ("COPY --link --from=" <> alias index source <> " " <> source.sourcePath <> " " <> source.targetPath)
      : fmap (renderSupport index source) source.supportCopies
  renderSupport index source support =
    "COPY --link --from=" <> alias index source <> " " <> support.sourcePath <> " " <> support.targetPath
  renderBuilt (_, built) =
    "COPY --link out/${TARGETARCH}/" <> built.name <> " " <> built.targetPath
  renderEnvironment environment = "ENV " <> environment.name <> "=\"" <> environment.value <> "\""

sanitize :: Text -> Text
sanitize = Text.map (\character -> if isAlphaNum character then character else 'x') . Text.toLower
