#!/usr/bin/env python3
"""Seeded negatives for the artifact-policy audit.

`development_plan_standards.md` section M clause 2 requires every gate to name at least
one committed seeded mutant it must turn red. This module is that mutant set for the
artifact-policy rules: one authored negative per rule, each asserted to be
reported **at its own rule**, so a rule that silently stops working fails here rather
than passing an audit it no longer performs. The count follows `policy.RULES`; adding a
rule without a negative here leaves it unproven and the surface join reports it.

The negatives drive the pure per-file scanners and the injectable audit entry points, so
none of them touches the real worktree.

    python3 tools/artifact_policy.py --self-test
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import artifact_policy as policy
import attestation
import attestation_negative_corpus
import artifact_manifest_lint as legacy
import containment


def _temporary_directory(prefix: str):
    root = policy.ROOT / ".build" / "tmp"
    root.mkdir(parents=True, exist_ok=True)
    return tempfile.TemporaryDirectory(prefix=prefix, dir=root)


def _rules(findings) -> set[str]:
    return {f.rule for f in findings}


def negative_r1_registry() -> policy.Report:
    """A doctrine output class with no registry row, and a tool inventing a class."""
    report = policy.Report()
    policy.audit_generator_registry(
        report,
        registry_text="runs/<phase>/<run-id>/**\ttools/doc_lint_verify.py\tphase-0\n",
        classes={"runs/<phase>/<run-id>/**", "tla/**/*.tla"},
    )
    policy.audit_generator_targets(
        report, {"runs"}, {"tools/synthetic_gate.py": 'OUT = ".build/invented/report.tsv"\n'}
    )
    return report


def negative_r2_provenance() -> policy.Report:
    """Three shapes of reproducible copy that no path rule would catch on its own."""
    report = policy.Report()
    report.findings.extend(
        policy.classify_tracked("test/golden/rendered.yaml", "# Generated by renderAll\nkey: 1\n")
    )
    report.findings.extend(
        policy.classify_tracked(
            "test/fixture/run.json",
            '{"phase":1,"gate_command":"x","register":"1","substrate":"none","date":"2026-01-01",'
            '"layers":[],"coverage":[],"ledger_hash":"sha256:0"}',
        )
    )
    report.findings.extend(
        policy.classify_tracked("test/fixture/copy.dhall", "let x = 1", twin=".build/dhall/copy.dhall")
    )
    return report


def negative_r3_ignore() -> policy.Report:
    """Both ignore contracts emptied: every normative pattern must be reported missing."""
    report = policy.Report()
    errors: list[str] = []
    legacy.audit_ignore_contract(errors, gitignore=set(), dockerignore=set())
    expected = len(legacy.GITIGNORE_REQUIRED_PATTERNS) + len(legacy.DOCKERIGNORE_REQUIRED_PATTERNS)
    if len(errors) != expected:
        report.findings.append(
            policy.Finding("r3", ".gitignore", f"expected {expected} missing patterns, got {len(errors)}")
        )
    else:
        report.findings.append(policy.Finding("r3", ".gitignore", "every normative pattern reported"))
    return report


def negative_r4_docker_context() -> policy.Report:
    """Generated output, run evidence, and a credential surviving into the context."""
    report = policy.Report()
    policy.audit_docker_context(
        report, [".build/runs/phase_00/ledger.json", "phase-results.tsv", "kubeconfig", "src/Main.hs"]
    )
    return report


def negative_r5_write_guard() -> policy.Report:
    """A write beneath an authored root, a generator declaring one, and a renamed root.

    The third case is the one the guard used to miss. A root that is no longer a
    directory — renamed, mistyped, or moved — simply dropped out of `authored_snapshot`,
    so the guard covered less and said nothing. Here the root is renamed on a synthetic
    tree and the audit must redden.
    """
    report = policy.Report()
    policy.audit_write_guard(
        report,
        {"documents/engineering/dsl_doctrine.md": "aaa"},
        {"documents/engineering/dsl_doctrine.md": "aaa", "documents/engineering/emitted.md": "bbb"},
    )
    policy.audit_write_locations(
        report,
        {
            "DEVELOPMENT_PLAN/evidence/phase_99/run.json": {"tools/synthetic_gate.py"},
            ".build/runs/phase_99/run.json": {"tools/synthetic_gate.py"},
        },
    )
    with _temporary_directory("amoebius-authored-root-negative-") as directory:
        tree = Path(directory)
        (tree / "documents").mkdir()
        (tree / "renamed-away").mkdir()  # what `src` became
        policy.audit_authored_roots(report, tree, ("documents", "src"))
    return report


def negative_r6_resolution() -> policy.Report:
    """A resolved home path, a package integrity pin, and an expected-digest table."""
    report = policy.Report()
    report.findings.extend(
        policy.scan_resolution("tools/synthetic_gate.py", 'GHC = "/home/someone/.ghcup/bin/ghc"\n')
    )
    report.findings.extend(
        policy.scan_resolution(
            "toolchain/synthetic.json",
            '{"url": "https://example.invalid/x.tar.gz", "sha256": "' + "a" * 64 + '"}',
        )
    )
    report.findings.extend(policy.scan_resolution("test/fixture/expected_hashes.tsv", "name\tvalue\n"))
    return report


def negative_r7_source_closure() -> policy.Report:
    """A build configuration whose input exists only as ignored worktree state."""
    # `.build/…` is ignored by construction and `src` is not, so the pair proves the audit
    # keys on the real ignore lookup rather than on the message it prints.
    report = policy.Report()
    policy.audit_source_closure(
        report,
        {
            ".build/synthetic-resolver-output.json": {"cabal.project"},
            "src": {"cabal.project"},
        },
    )
    return report


def negative_r8_history() -> policy.Report:
    """A credential in history, and a generated blob with no recorded disposition."""
    report = policy.Report()
    policy.audit_revision_history(
        report, {"deploy/id_rsa", "build/synthetic-artifact.freeze", "src/Main.hs"}
    )
    return report


def negative_r9_attestation() -> policy.Report:
    """Every bundle in the negative corpus must be refused before it is stored."""
    report = policy.Report()
    with _temporary_directory("amoebius-attest-negative-") as directory:
        store = attestation.Store(Path(directory))
        positive = attestation.sample_bundle()
        refused = 0
        for _name, broken, _expect in attestation_negative_corpus.negative_corpus(positive):
            if attestation.schema_check(broken):
                refused += 1
                continue
            try:
                store.put(broken)
            except attestation.AttestationError:
                refused += 1
        total = len(attestation_negative_corpus.negative_corpus(positive))
        if refused == total:
            report.findings.append(
                policy.Finding("r9", "run-bundle", f"all {total} negative bundles refused")
            )
    return report


def negative_r10_terminology() -> policy.Report:
    """The retired predecessor name, in a pathname and in file content."""
    report = policy.Report()
    errors: list[str] = []
    retired = "mid" + "wife"
    with _temporary_directory("amoebius-terminology-negative-") as directory:
        fixture = Path(directory) / f"legacy-{retired}.py"
        fixture.write_text(retired + "\n", encoding="utf-8")
        legacy.audit_bootstrap_coordinator_terminology(errors, paths=[fixture])
    for error in errors:
        locus, _, message = error.partition(": ")
        report.findings.append(policy.Finding("r10", locus, message))
    return report


def negative_r11_no_leak() -> policy.Report:
    """A run that leaves an unignored path behind, and one that dirties a tracked file."""
    report = policy.Report()
    policy.audit_clean_tree(
        report,
        {"src/Main.hs": " M"},
        {"src/Main.hs": "MM", "tools/leaked-output.tsv": "??"},
    )
    return report


def negative_r12_corpora() -> policy.Report:
    """The three ways a corpus declaration decays: unknown rule, dead path, dead row.

    The fourth shape — a corpus that suppresses the rule it declares — is the positive
    control, and it is asserted to leave `r12` silent.
    """
    report = policy.Report()
    live = policy.Corpus("tools/ledger_lint_corpus/", frozenset({"r2"}))
    stale_rule = policy.Corpus("tools/ledger_lint_corpus/", frozenset({"r99"}))
    absent = policy.Corpus("tools/no_such_corpus.py", frozenset({"r6"}))
    unused = policy.Corpus("tools/attestation_negative_corpus.py", frozenset({"r5"}))

    seeded = policy.Report()
    seeded.findings.append(
        policy.Finding("r2", "tools/ledger_lint_corpus/positive.json", "tracked JSON has the run-ledger shape")
    )
    policy.apply_corpora(seeded, [live])
    if seeded.findings:
        report.findings.append(
            policy.Finding("r12", "positive", "a declared corpus failed to suppress its own seed")
        )
    policy.audit_corpus_integrity(report, [live, stale_rule, absent, unused])
    return report


SYNTHETIC_TREE = """
```text
amoebius/
├── .gitignore                            authored worktree policy
├── DEVELOPMENT_PLAN/**                   authored plan suite
├── src/**                                authored Haskell library source
├── test/**                               authored specs, fixtures, goldens
├── .build/**                             every reproducible local output; ignored by both contracts
├── .data/**                              production runtime state; ignored by both contracts
└── .test_data/**                         harness-owned test state; ignored by both contracts
```

Two roots fix a second level:

```text
test/
├── fixture/**                            authored positive inputs
└── golden/**                             authored expected outputs
```
"""


def synthetic_tree() -> policy.TargetTree:
    """A four-root tree in the section-2 dialect, so the negatives never read doctrine.

    The parser is exercised against the real document by the audit itself; here the point
    is the membership decision, and a fixture tree makes each rejection reason explicit
    instead of implying it from whatever the repository happens to contain today.
    """
    return policy.parse_target_tree(policy.TREE_HEADING + SYNTHETIC_TREE + policy.TREE_STOP)


def negative_r13_target_tree() -> policy.Report:
    """An undeclared root, a stray root-level file, and a non-role second level."""
    report = policy.Report()
    policy.audit_target_tree(
        report,
        [
            "src/Amoebius/Kernel.hs",
            ".build/runs/documentation_suite/ledger.json",
            "scratch/notes.md",
            "LICENCE.txt",
            "test/fixture/spec.dhall",
            "test/golden/rendered.yaml",
        ],
        synthetic_tree(),
    )
    return report


def negative_r14_ignore_partition() -> policy.Report:
    """A rule beneath an authored root, one for a root the tree lacks, both syntaxes."""
    report = policy.Report()
    policy.audit_ignore_partition(
        report,
        [
            (".gitignore", "/.build/"),
            (".gitignore", "*.o"),
            (".gitignore", "/src/generated/"),
            (".gitignore", "/scratch/"),
            (".dockerignore", ".build/**"),
            (".dockerignore", "**/*.o"),
            (".dockerignore", "scratch"),
        ],
        synthetic_tree(),
    )
    return report


def negative_r15_phase_ordinal() -> policy.Report:
    """An ordinal in a path, a build flag, a suite name, and an ignore rule."""
    report = policy.Report()
    policy.audit_phase_ordinals(
        report,
        ["tools/capacity_topology_gate.py", "DEVELOPMENT_PLAN/phase_14_capacity_core_folds.md", "src/Kernel.hs"],
        "flag phase7-fold-mutant\n  default: False\ntest-suite phase7-capacity-spec\nlibrary amoebius\n",
        [(".gitignore", "/.phase7-store/"), (".gitignore", "/.build/")],
    )
    return report


def negative_r16_state_containment() -> policy.Report:
    """System paths, production/test aliasing, global Docker, and marker tampering."""
    report = policy.Report()

    def rejected(locus: str, action) -> None:
        try:
            action()
        except containment.ContainmentError as exc:
            report.findings.append(policy.Finding("r16", locus, str(exc)))

    rejected(
        "synthetic-output",
        lambda: containment.require_state_path("/tmp/amoebius-output", "build", actor="production"),
    )
    rejected(
        "synthetic-production-home",
        lambda: containment.require_state_path(
            "/home/operator/.amoebius/runtime", "production", actor="production"
        ),
    )
    rejected(
        "synthetic-test-alias",
        lambda: containment.require_state_path(".data/test-run", "production", actor="test"),
    )
    rejected(
        "synthetic-global-docker",
        lambda: containment.require_project_resource(
            "docker-container", "/var/lib/docker", scope="host-global"
        ),
    )

    # The positive exercises real marker-owned creation and exact-path cleanup.  The
    # mutation between them must be refused before deletion, then the original marker
    # is restored so this seeded negative leaves no run descendant behind.
    import uuid

    run = containment.create_test_run("policy-" + uuid.uuid4().hex)
    marker = run.path / containment.MARKER
    original = marker.read_bytes()
    marker.write_bytes(original + b"changed\n")
    rejected("synthetic-changed-marker", lambda: containment.cleanup_test_run(run))
    marker.write_bytes(original)
    containment.cleanup_test_run(run)

    contained = containment.state_path("build", "tmp", "positive", actor="production")
    containment.require_state_path(contained, "build", actor="production")
    return report


def negative_r17_test_secrets() -> policy.Report:
    """Production access and a filesystem copy of the test seam are both refused."""
    report = policy.Report()
    for locus, action in (
        (
            "synthetic-production-secret-read",
            lambda: containment.require_secret_access("production"),
        ),
        (
            "synthetic-secret-copy",
            lambda: containment.require_secret_sink(".build/tmp/copied-secret"),
        ),
    ):
        try:
            action()
        except containment.ContainmentError as exc:
            report.findings.append(policy.Finding("r17", locus, str(exc)))
    return report


NEGATIVES = {
    "r1": ("registry_class_unowned", negative_r1_registry),
    "r2": ("tracked_reproducible_copy", negative_r2_provenance),
    "r3": ("ignore_patterns_removed", negative_r3_ignore),
    "r4": ("context_carries_generated", negative_r4_docker_context),
    "r5": ("write_beneath_authored_root", negative_r5_write_guard),
    "r6": ("resolved_path_and_pin", negative_r6_resolution),
    "r7": ("ignored_build_input", negative_r7_source_closure),
    "r8": ("history_secret_and_blob", negative_r8_history),
    "r9": ("malformed_run_bundle", negative_r9_attestation),
    "r10": ("retired_predecessor_name", negative_r10_terminology),
    "r11": ("gate_leaks_output", negative_r11_no_leak),
    "r12": ("stale_corpus_exemption", negative_r12_corpora),
    "r13": ("path_outside_target_tree", negative_r13_target_tree),
    "r14": ("ignore_rule_off_tree", negative_r14_ignore_partition),
    "r15": ("phase_ordinal_in_name", negative_r15_phase_ordinal),
    "r16": ("state_escapes_checkout", negative_r16_state_containment),
    "r17": ("production_test_secret", negative_r17_test_secrets),
}


def run() -> bool:
    ok = True
    print(f"policy side — {len(NEGATIVES)} seeded negatives, one per rule\n")
    for rule, (name, build) in NEGATIVES.items():
        report = build()
        hit = _rules(report.findings)
        if not report.findings:
            print(f"  FAIL  {name:34s} {rule} stayed clean")
            ok = False
        elif hit != {rule}:
            print(f"  FAIL  {name:34s} expected only {rule}, got {', '.join(sorted(hit))}")
            ok = False
        else:
            print(f"  ok    {name:34s} {rule}  ({len(report.findings)} finding(s))")
    return ok


if __name__ == "__main__":
    raise SystemExit(0 if run() else 1)
