#!/usr/bin/env python3
"""Seeded negatives for the artifact-policy audit.

`development_plan_standards.md` section M clause 2 requires every gate to name at least
one committed seeded mutant it must turn red. This module is that mutant set for the
eleven artifact-policy rules: one authored negative per rule, each asserted to be
reported **at its own rule**, so a rule that silently stops working fails here rather
than passing an audit it no longer performs.

The negatives drive the pure per-file scanners and the injectable audit entry points, so
none of them touches the real worktree.

    python3 tools/artifact_policy.py --self-test
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import artifact_policy as policy
import attestation
import phase0_artifact_lint as legacy


def _rules(findings) -> set[str]:
    return {f.rule for f in findings}


def negative_r1_registry() -> policy.Report:
    """A doctrine output class with no registry row, and a tool inventing a class."""
    report = policy.Report()
    policy.audit_generator_registry(
        report,
        registry_text="runs/<phase>/<run-id>/**\ttools/doc_lint_verify.py\tphase-0\n",
        classes={"runs/<phase>/<run-id>/**", "tla/**/*.tla"},
    )
    policy.audit_generator_targets(
        report, {"runs"}, {"tools/synthetic_gate.py": 'OUT = "gen/invented/report.tsv"\n'}
    )
    return report


def negative_r2_provenance() -> policy.Report:
    """Three shapes of reproducible copy that no path rule would catch on its own."""
    report = policy.Report()
    report.findings.extend(
        policy.classify_tracked("test/golden/rendered.yaml", "# Generated by renderAll\nkey: 1\n")
    )
    report.findings.extend(
        policy.classify_tracked(
            "test/fixtures/run.json",
            '{"phase":1,"gate_command":"x","register":"1","substrate":"none","date":"2026-01-01",'
            '"layers":[],"coverage":[],"ledger_hash":"sha256:0"}',
        )
    )
    report.findings.extend(
        policy.classify_tracked("test/fixtures/copy.dhall", "let x = 1", twin="gen/dhall/copy.dhall")
    )
    return report


def negative_r3_ignore() -> policy.Report:
    """Both ignore contracts emptied: every normative pattern must be reported missing."""
    report = policy.Report()
    errors: list[str] = []
    legacy.audit_ignore_contract(errors, gitignore=set(), dockerignore=set())
    expected = len(legacy.GITIGNORE_REQUIRED_PATTERNS) + len(legacy.DOCKERIGNORE_REQUIRED_PATTERNS)
    if len(errors) != expected:
        report.findings.append(
            policy.Finding("r3", ".gitignore", f"expected {expected} missing patterns, got {len(errors)}")
        )
    else:
        report.findings.append(policy.Finding("r3", ".gitignore", "every normative pattern reported"))
    return report


def negative_r4_docker_context() -> policy.Report:
    """Generated output, run evidence, and a credential surviving into the context."""
    report = policy.Report()
    policy.audit_docker_context(
        report, ["gen/runs/phase_00/ledger.json", "phase-results.tsv", "kubeconfig", "src/Main.hs"]
    )
    return report


def negative_r5_write_guard() -> policy.Report:
    """A generator that writes beneath an authored root, and one that declares it."""
    report = policy.Report()
    policy.audit_write_guard(
        report,
        {"documents/engineering/dsl_doctrine.md": "aaa"},
        {"documents/engineering/dsl_doctrine.md": "aaa", "documents/engineering/emitted.md": "bbb"},
    )
    policy.audit_write_locations(
        report,
        {
            "DEVELOPMENT_PLAN/evidence/phase_99/run.json": {"tools/synthetic_gate.py"},
            "gen/runs/phase_99/run.json": {"tools/synthetic_gate.py"},
        },
    )
    return report


def negative_r6_resolution() -> policy.Report:
    """A resolved home path, a package integrity pin, and an expected-digest table."""
    report = policy.Report()
    report.findings.extend(
        policy.scan_resolution("tools/synthetic_gate.py", 'GHC = "/home/someone/.ghcup/bin/ghc"\n')
    )
    report.findings.extend(
        policy.scan_resolution(
            "toolchain/synthetic.json",
            '{"url": "https://example.invalid/x.tar.gz", "sha256": "' + "a" * 64 + '"}',
        )
    )
    report.findings.extend(policy.scan_resolution("test/fixtures/expected_hashes.tsv", "name\tvalue\n"))
    return report


def negative_r7_source_closure() -> policy.Report:
    """A build configuration whose input exists only as ignored worktree state."""
    # `gen/…` is ignored by construction and `src` is not, so the pair proves the audit
    # keys on the real ignore lookup rather than on the message it prints.
    report = policy.Report()
    policy.audit_source_closure(
        report,
        {
            "gen/synthetic-resolver-output.json": {"cabal.project"},
            "src": {"cabal.project"},
        },
    )
    return report


def negative_r8_history() -> policy.Report:
    """A credential in history, and a generated blob with no recorded disposition."""
    report = policy.Report()
    policy.audit_revision_history(
        report, {"deploy/id_rsa", "build/synthetic-artifact.freeze", "src/Main.hs"}
    )
    return report


def negative_r9_attestation() -> policy.Report:
    """Every bundle in the negative corpus must be refused before it is stored."""
    report = policy.Report()
    with tempfile.TemporaryDirectory(prefix="amoebius-attest-negative-") as directory:
        store = attestation.Store(Path(directory))
        positive = attestation.sample_bundle()
        refused = 0
        for _name, broken, _expect in attestation.negative_corpus(positive):
            if attestation.schema_check(broken):
                refused += 1
                continue
            try:
                store.put(broken)
            except attestation.AttestationError:
                refused += 1
        total = len(attestation.negative_corpus(positive))
        if refused == total:
            report.findings.append(
                policy.Finding("r9", "run-bundle", f"all {total} negative bundles refused")
            )
    return report


def negative_r10_terminology() -> policy.Report:
    """The retired predecessor name, in a pathname and in file content."""
    report = policy.Report()
    errors: list[str] = []
    retired = "mid" + "wife"
    with tempfile.TemporaryDirectory(prefix="amoebius-terminology-negative-") as directory:
        fixture = Path(directory) / f"legacy-{retired}.py"
        fixture.write_text(retired + "\n", encoding="utf-8")
        legacy.audit_bootstrap_coordinator_terminology(errors, paths=[fixture])
    for error in errors:
        locus, _, message = error.partition(": ")
        report.findings.append(policy.Finding("r10", locus, message))
    return report


def negative_r11_no_leak() -> policy.Report:
    """A run that leaves an unignored path behind, and one that dirties a tracked file."""
    report = policy.Report()
    policy.audit_clean_tree(
        report,
        {"src/Main.hs": " M"},
        {"src/Main.hs": "MM", "tools/leaked-output.tsv": "??"},
    )
    return report


NEGATIVES = {
    "r1": ("registry_class_unowned", negative_r1_registry),
    "r2": ("tracked_reproducible_copy", negative_r2_provenance),
    "r3": ("ignore_patterns_removed", negative_r3_ignore),
    "r4": ("context_carries_generated", negative_r4_docker_context),
    "r5": ("write_beneath_authored_root", negative_r5_write_guard),
    "r6": ("resolved_path_and_pin", negative_r6_resolution),
    "r7": ("ignored_build_input", negative_r7_source_closure),
    "r8": ("history_secret_and_blob", negative_r8_history),
    "r9": ("malformed_run_bundle", negative_r9_attestation),
    "r10": ("retired_predecessor_name", negative_r10_terminology),
    "r11": ("gate_leaks_output", negative_r11_no_leak),
}


def run() -> bool:
    ok = True
    print(f"policy side — {len(NEGATIVES)} seeded negatives, one per rule\n")
    for rule, (name, build) in NEGATIVES.items():
        report = build()
        hit = _rules(report.findings)
        if not report.findings:
            print(f"  FAIL  {name:34s} {rule} stayed clean")
            ok = False
        elif hit != {rule}:
            print(f"  FAIL  {name:34s} expected only {rule}, got {', '.join(sorted(hit))}")
            ok = False
        else:
            print(f"  ok    {name:34s} {rule}  ({len(report.findings)} finding(s))")
    return ok


if __name__ == "__main__":
    raise SystemExit(0 if run() else 1)
