#!/bin/sh
set -eu
tool="${0##*/}"
counter_path="$AMOEBIUS_TRANSCRIPT_DIR/$tool.count"
count=0
if [ -f "$counter_path" ]; then IFS= read -r count < "$counter_path"; fi
count=$((count + 1))
printf '%s\n' "$count" > "$counter_path"
argv_path="$AMOEBIUS_TRANSCRIPT_DIR/$tool.$count.argv"
stdin_path="$AMOEBIUS_TRANSCRIPT_DIR/$tool.$count.stdin"
printf '%s\n' "$0" "$@" > "$argv_path"
/usr/bin/dd of="$stdin_path" status=none
printf '%s\n' 'fake-tool: unexpected helm invocation'
