name: Build Marp Slides

on:
  push:
    branches: [ main ]
    paths: 
      - 'presentation/**'
      - '.github/workflows/marp-slides.yml'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli
        
      - name: Build presentation
        run: |
          mkdir -p docs
          marp presentation/slides.md --html --output docs/index.html --no-stdin
          cp -r presentation/assets docs/
          
      - name: Commit built files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --staged --quiet || git commit -m "Build presentation [skip ci]"
          git push