name: Build and Deploy Marp Slides

on:
  push:
    branches: [ main ]
    paths: 
      - 'presentation/**'
      - '.github/workflows/marp-slides.yml'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create docs directory
        run: mkdir -p docs
        
      - name: Build slides with Marp
        uses: docker://marpteam/marp-cli:latest
        with:
          args: presentation/slides.md --html --output docs/index.html --theme default
          
      - name: Copy assets
        run: |
          cp -r presentation/assets docs/
          
      - name: Commit and push to gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Deploy presentation" || echo "No changes to commit"
          git push origin main